[workspace]
members = [
    "./actix-hash",
    "./actix-web-lab",
    "./actix-web-lab-derive",
]
resolver = "2"

[patch.crates-io]
actix-hash = { path = "./actix-hash" }
actix-web-lab = { path = "./actix-web-lab" }
actix-web-lab-derive = { path = "./actix-web-lab-derive" }
