version: 2.1

jobs:
  clippy:
    docker:
      - image: cimg/rust:1.58.0
    steps:
      - checkout
      - run: cargo --version
      - restore_cache:
          key: clippy-cache
      - run: cargo clippy --workspace --all-targets --all-features
      - save_cache:
          key: clippy-cache
          paths:
            - "~/.cargo"
            - "./target"

  test:
    docker:
      - image: cimg/rust:1.58.0
    steps:
      - checkout
      - run: cargo --version
      - restore_cache:
          key: test-cache
      - run: |
          cargo test --workspace --all-targets --all-features
          cargo test --workspace --doc --all-features
      - save_cache:
          key: test-cache
          paths:
            - "~/.cargo"
            - "./target"

workflows:
  version: 2
  all_checks:
    jobs:
      - clippy: { filters: { branches: { ignore: 'rustdoc-gh-pages' } } }
      - test: { filters: { branches: { ignore: 'rustdoc-gh-pages' } } }
